name: secure_sg_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/background_full.png
    - assets/images/background.png
    - assets/images/badminton.png
    - assets/images/basket.png
    - assets/images/cl_icon.png
    - assets/images/claim.png
    - assets/images/default_bg.png
    - assets/images/ea_bg.png
